# -*- coding: utf-8 -*-
"""setup.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2YmQe4HIOec_x9t_OfkwkDwZkwPoYTy
"""

from setuptools import setup

setup(
   name='testing1',
   version='1.0',
   description='A useful module',
   author='Author Name',
   author_email='merkulov.dmit@gmail.com',
   packages=['testing1'],  #same as name
   install_requires=['numpy', 'pandas'], #external packages as dependencies
)

import numpy
import pandas

def f_sum(a, b):
    return a + b