# -*- coding: utf-8 -*-
"""init

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDKkW6jvy8SgTNraZnEehh9yGqzy2bji
"""

import numpy
import pandas

def __init__(self, color, brand):
    self.color = color
    self.brand = brand

def f_sum(a, b):
    return a + b
